### ISSUE TITLE
Changing configs in the server does not apply them on the client

### ISSUE THREAD

**Issue by Snivine** [RCXcrafter/TweakersConstruct#43]
I installed the mod to tweak a material that had an OP trait but it seems that the mod disabled the mending moss

I tried to readd the mending moss modifier but it didn't work, not even removing the mod did, is there a way to fix this?

**Comment by Snivine** [comment]
seems to be related with #25, I'm gonna do some testing

**Comment by Snivine** [comment]
yes it is related to #25, I'm going to leave it open so it is addressed

**Comment by RCXcrafter** [comment]
How is it related, did you remove mending moss from the client config while it was still set in the config on the server?

**Comment by Snivine** [comment]
no, I set mending moss as available in the server config, but it didn't updated in the client config so I couldn't use it, after changing it in the client config I could use it

**Comment by RCXcrafter** [comment]
I see, there's not really anything I can do about that. Tweakers construct makes most of its tweaks when minecraft starts up, so when joining a server most of the tweaked things are already set in stone. It would be technically possible to change things after that but it would be diffucult and tinkers construct does not expect that to happen so it would probably cause a whole bunch of bugs that I don't want to fix.
Anyway, since you figured out why it wasn't working I'll close this issue.
